version: '3.8'

services:
  db:
    image: postgres:15
    container_name: projects_tasks_db
    environment:
      POSTGRES_DB: projects_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    container_name: projects_tasks_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/projects_tasks
      JWT_SECRET: your_jwt_secret
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db

  web:
    build: ./apps/web
    container_name: projects_tasks_web
    environment:
      NEXT_PUBLIC_API_URL: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
